amcl:
  ros__parameters:
    use_sim_time: False
    alpha1: 0.01       # Öne/arkaya kayma gürültüsü (düşürüldü)
    alpha2: 0.01       # Dönüş gürültüsü (düşürüldü)
    alpha3: 0.01       # Düşürüldü
    alpha4: 0.01       # Düşürüldü
    alpha5: 0.01       # Dönüş sonrası tekrar doğruluk (düşürüldü)
    base_frame_id: "base_link"
    global_frame_id: "map"
    laser_likelihood_max_dist: 1.0    # Lazer okumalarını 1 m'de sabitle
    laser_max_range: 20.0
    laser_min_range: 0.1
    laser_model_type: "likelihood_field"
    max_beams: 40                    # Işın sayısı azaltıldı
    max_particles: 500               # Particle sayısı azaltıldı
    min_particles: 200               # Minimum particle sayısı azaltıldı
    resample_interval: 4             # Yeniden örnekleme aralığı artırıldı
    odom_frame_id: "odom"
    robot_model_type: "nav2_amcl::DifferentialMotionModel"
    sigma_hit: 0.2                   # Ölçüm gürültüsü toleransı artırıldı
    z_hit: 0.7                       # Lazer okumalarına ağırlık azaltıldı
    z_rand: 0.2                      # Rastgele ölçüm ağırlığı artırıldı
    tf_broadcast: true
    transform_tolerance: 0.1

controller_server:
  ros__parameters:
    use_sim_time: False
    controller_frequency: 20.0      # Daha hızlı kontrol döngüsü
    min_x_velocity_threshold: 0.01
    min_y_velocity_threshold: 0.05
    min_theta_velocity_threshold: 0.01
    failure_tolerance: 0.3
    progress_checker_plugin: "progress_checker"
    goal_checker_plugins: ["general_goal_checker"]
    controller_plugins: ["FollowPath"]

    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
      required_movement_radius: 0.5
      movement_time_allowance: 10.0

    general_goal_checker:
      stateful: True
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance: 0.05          # Hedef toleransı 5 cm
      yaw_goal_tolerance: 0.10         # Yaw toleransı 0.1 rad

    FollowPath:
      plugin: "dwb_core::DWBLocalPlanner"
      debug_trajectory_details: True
      min_vel_x: 0.0
      max_vel_x: 0.8
      max_vel_theta: 1.0
      acc_lim_x: 3.0
      decel_lim_x: -3.0
      acc_lim_theta: 8.0
      decel_lim_theta: -5.0
      vx_samples: 30
      vtheta_samples: 150
      sim_time: 1.0
      linear_granularity: 0.02
      angular_granularity: 0.01
      transform_tolerance: 0.1
      xy_goal_tolerance: 0.05
      trans_stopped_velocity: 0.05

      critics: ["RotateToGoal", "Oscillation", "BaseObstacle", "GoalAlign", "PathAlign", "PathDist", "GoalDist"]
      BaseObstacle.scale: 0.05
      PathAlign.scale: 40.0
      GoalAlign.scale: 40.0
      PathDist.scale: 40.0
      GoalDist.scale: 40.0
      RotateToGoal.scale: 40.0

local_costmap:
  local_costmap:
    ros__parameters:
      use_sim_time: False
      update_frequency: 10.0          # 10 Hz ile daha hızlı güncelleme
      publish_frequency: 5.0
      global_frame: odom
      robot_base_frame: base_link
      rolling_window: true
      width: 3.0
      height: 3.0
      resolution: 0.02                # 2 cm çözünürlük
      robot_radius: 0.35

      plugins: ["obstacle_layer", "inflation_layer"]
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        observation_sources: scan2
        scan2:
          topic: /scan2
          max_obstacle_height: 2.0
          marking: True
          clearing: True
          data_type: "LaserScan"
          raytrace_max_range: 3.0
          obstacle_max_range: 2.5

      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        inflation_radius: 0.30          # Daha sıkı güvenlik alanı
        cost_scaling_factor: 2.0

global_costmap:
  global_costmap:
    ros__parameters:
      use_sim_time: False
      update_frequency: 2.0
      publish_frequency: 2.0
      global_frame: map
      robot_base_frame: base_link
      resolution: 0.02
      track_unknown_space: true
      plugins: ["static_layer", "obstacle_layer", "inflation_layer"]
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        observation_sources: scan2
        scan2:
          topic: /scan2
          raytrace_max_range: 20.0
          obstacle_max_range: 20.0
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        inflation_radius: 0.40
        cost_scaling_factor: 2.5

planner_server:
  ros__parameters:
    expected_planner_frequency: 20.0
    use_sim_time: False
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_navfn_planner/NavfnPlanner"
      tolerance: 0.20                  # Hedef toleransı 20 cm
      use_astar: false
      allow_unknown: true 